# RNN shapes

In [1]:
import tensorflow as tf

from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt

In [2]:
tf.__version__

'2.1.0'

Dimension nomenclature:
* $N =$ number of samples
* $T =$ sequence length
* $D =$ number of input features
* $M =$ number of hidden units (or nodes or neurons)
* $K =$ number of ouput units

Make some data:

In [13]:
N = 2
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

Make an RNN:

In [14]:
M: int = 5
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

Make a prediction using the RNN:

In [15]:
Yhat = model.predict(X)
print(Yhat)

[[-0.8254827 -2.1485028]
 [-1.7451695 -1.1191165]]


In [6]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn (SimpleRNN)       (None, 5)                 45        
_________________________________________________________________
dense (Dense)                (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.layers[1].get_weights()

[array([[ 0.8251191 ,  0.8227975 , -0.27566206,  0.11379337, -0.20640612],
        [-0.1691978 ,  0.01490659, -0.72974527,  0.4987629 , -0.2166329 ],
        [ 0.7503329 , -0.6101254 ,  0.4595613 , -0.64288473, -0.14092416]],
       dtype=float32),
 array([[-0.35479903, -0.34857222,  0.32226896, -0.5846935 ,  0.5539776 ],
        [-0.11464607,  0.5062352 ,  0.57921183, -0.3842737 , -0.497423  ],
        [ 0.6190153 , -0.6320808 ,  0.30645776, -0.13652343, -0.3236339 ],
        [ 0.12166765,  0.11019716,  0.6701154 ,  0.60557526,  0.3965823 ],
        [-0.68043435, -0.45886135,  0.13298605,  0.35370502, -0.42855898]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [10]:
a, b, c = model.layers[1].get_weights()
print(f"input-to-hidden shape: {a.shape}, hidden-to-hidden shape: {b.shape}, output shape: {c.shape}")

input-to-hidden shape: (3, 5), hidden-to-hidden shape: (5, 5), output shape: (5,)


In [11]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [12]:
h_last = np.zeros(M)  # initial hidden state
x = X[0]  # the one and only sample
Yhats = []  # where we store the outputs

for t in range(T):
    h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
    y = h.dot(Wo) + bo  # we only care about this value on the last iteration
    Yhats.append(y)
    h_last = h

# print the final output
print(Yhats[-1])

[-0.72581142 -0.96377373]
